-- MySQL Script generated by MySQL Workbench
-- Sat Sep 22 18:38:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema piatest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `piatest` ;

-- -----------------------------------------------------
-- Schema piatest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piatest` DEFAULT CHARACTER SET utf8 ;
USE `piatest` ;

-- -----------------------------------------------------
-- Table `piatest`.`fill_ft_guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`fill_ft_guest` ;

CREATE TABLE IF NOT EXISTS `piatest`.`fill_ft_guest` (
  `id` INT(11) NOT NULL,
  `prevoznik` VARCHAR(45) NULL DEFAULT NULL,
  `pocetna` VARCHAR(45) NULL DEFAULT NULL,
  `odredisna` VARCHAR(45) NULL DEFAULT NULL,
  `polazak` VARCHAR(45) NULL DEFAULT NULL,
  `dolazak` VARCHAR(45) NULL DEFAULT NULL,
  `vozac_id` INT(11) NULL DEFAULT NULL,
  `autobus_id` INT(11) NULL DEFAULT NULL,
  `vozac` VARCHAR(45) NULL DEFAULT NULL,
  `autobus` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`stanice_gr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`stanice_gr` ;

CREATE TABLE IF NOT EXISTS `piatest`.`stanice_gr` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_naziv` (`naziv` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`stanice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`stanice` ;

CREATE TABLE IF NOT EXISTS `piatest`.`stanice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupa_id` INT(11) DEFAULT 0,
  `rbr` INT(11),
  `naziv` VARCHAR(45) NOT NULL,
  `sirina` DECIMAL(11,2) NULL DEFAULT '0.00',
  `duzina` DECIMAL(11,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `FK_stanica_grupa` (`grupa_id` ASC),
  CONSTRAINT `FK_stanica_grupa`
    FOREIGN KEY (`grupa_id`)
    REFERENCES `piatest`.`stanice_gr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`gradske_linije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`gradske_linije` ;

CREATE TABLE IF NOT EXISTS `piatest`.`gradske_linije` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rbr` INT(11) NOT NULL,
  `id_polaziste` INT(11) NOT NULL,
  `id_odrediste` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rbr_UNIQUE` (`rbr` ASC),
  INDEX `idPolaz_idx` (`id_polaziste` ASC),
  INDEX `idOdr_idx` (`id_odrediste` ASC),
  CONSTRAINT `idOdr`
    FOREIGN KEY (`id_odrediste`)
    REFERENCES `piatest`.`stanice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPolaz`
    FOREIGN KEY (`id_polaziste`)
    REFERENCES `piatest`.`stanice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`korisnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`korisnici` ;

CREATE TABLE IF NOT EXISTS `piatest`.`korisnici` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL DEFAULT NULL,
  `prezime` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `adresa` VARCHAR(45) NULL DEFAULT NULL,
  `datum` DATE NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `zaposlenje` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `odobren` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`linije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`linije` ;

CREATE TABLE IF NOT EXISTS `piatest`.`linije` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stanica0_id` INT(11) NOT NULL,
  `stanica1_id` INT(11) NOT NULL,
  `rbr` INT(11) NOT NULL,
  `opis` VARCHAR(45) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`linije_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`linije_det` ;

CREATE TABLE IF NOT EXISTS `piatest`.`linije_det` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `linija_id` INT(11) NOT NULL,
  `stanica_id` INT(11) NOT NULL,
  `rbr` INT(11) NOT NULL,
  `pocetna_krajnja` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `FK_linijedet_linija` (`linija_id` ASC),
  INDEX `FK_linijedet_stanice` (`stanica_id` ASC),
  CONSTRAINT `FK_linijedet_linija`
    FOREIGN KEY (`linija_id`)
    REFERENCES `piatest`.`linije` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_linijedet_stanice`
    FOREIGN KEY (`stanica_id`)
    REFERENCES `piatest`.`stanice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 134
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`medjustanice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`medjustanice` ;

CREATE TABLE IF NOT EXISTS `piatest`.`medjustanice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prod_id` INT(11) NOT NULL,
  `medjustanica` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`otkazane_linije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`otkazane_linije` ;

CREATE TABLE IF NOT EXISTS `piatest`.`otkazane_linije` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rbrLinije` INT(11) NOT NULL,
  `od` DATE NULL DEFAULT NULL,
  `do` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rbr_idx` (`rbrLinije` ASC),
  CONSTRAINT `rbrOtkazane`
    FOREIGN KEY (`rbrLinije`)
    REFERENCES `piatest`.`gradske_linije` (`rbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`prevoznik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`prevoznik` ;

CREATE TABLE IF NOT EXISTS `piatest`.`prevoznik` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NULL DEFAULT NULL,
  `kontakt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_naziv` (`naziv` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`prevoznik_autobusi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`prevoznik_autobusi` ;

CREATE TABLE IF NOT EXISTS `piatest`.`prevoznik_autobusi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prevoznik_id` INT(11) NOT NULL,
  `rbr` INT(11) NOT NULL,
  `marka` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `sedista` INT(11) NOT NULL,
  `foto1` LONGBLOB NULL DEFAULT NULL,
  `foto2` LONGBLOB NULL DEFAULT NULL,
  `foto3` LONGBLOB NULL DEFAULT NULL,
  `foto4` LONGBLOB NULL DEFAULT NULL,
  `foto5` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `prevoznik_bus_idx` (`prevoznik_id` ASC),
  CONSTRAINT `FK_bus_prevoznik`
    FOREIGN KEY (`prevoznik_id`)
    REFERENCES `piatest`.`prevoznik` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`prevoznik_vozaci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`prevoznik_vozaci` ;

CREATE TABLE IF NOT EXISTS `piatest`.`prevoznik_vozaci` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prevoznik_id` INT(11) NOT NULL,
  `rbr` INT(11) NULL DEFAULT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `dtmrodjenja` DATE NOT NULL,
  `dtmpocetka` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `prevoznik_vozac_idx` (`prevoznik_id` ASC),
  CONSTRAINT `FK_vozac_prevoznik`
    FOREIGN KEY (`prevoznik_id`)
    REFERENCES `piatest`.`prevoznik` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`prod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`prod` ;

CREATE TABLE IF NOT EXISTS `piatest`.`prod` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `linija_id` INT(11) NOT NULL,
  `vozac_id` INT(11) NOT NULL,
  `autobus_id` INT(11) NULL DEFAULT NULL,
  `rbr` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_prod_vozac` (`linija_id` ASC),
  INDEX `FK_prod_linija` (`vozac_id` ASC),
  INDEX `FK_prod_bus` (`autobus_id` ASC),
  CONSTRAINT `FK_prod_bus`
    FOREIGN KEY (`autobus_id`)
    REFERENCES `piatest`.`prevoznik_autobusi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_prod_linija`
    FOREIGN KEY (`vozac_id`)
    REFERENCES `piatest`.`prevoznik_vozaci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_prod_vozac`
    FOREIGN KEY (`linija_id`)
    REFERENCES `piatest`.`linije` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`prod_det`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`prod_det` ;

CREATE TABLE IF NOT EXISTS `piatest`.`prod_det` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `prod_id` INT(11) NOT NULL,
  `linijedet_id` INT(11) NOT NULL,
  `rbr` INT(11) NOT NULL,
  `dolazak` DATETIME NULL,
  `polazak` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_proddet_prod` (`prod_id` ASC),
  INDEX `FK_proddet_linijedet` (`linijedet_id` ASC),
  CONSTRAINT `FK_proddet_linijedet`
    FOREIGN KEY (`linijedet_id`)
    REFERENCES `piatest`.`linije_det` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_proddet_prod`
    FOREIGN KEY (`prod_id`)
    REFERENCES `piatest`.`prod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`red_voznje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`red_voznje` ;

CREATE TABLE IF NOT EXISTS `piatest`.`red_voznje` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medjustanica` INT(11) NOT NULL,
  `rbr_linije` INT(11) NOT NULL,
  `polazak` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idMedjustanice_idx` (`id_medjustanica` ASC),
  INDEX `RBR_idx` (`rbr_linije` ASC),
  CONSTRAINT `RBR`
    FOREIGN KEY (`rbr_linije`)
    REFERENCES `piatest`.`gradske_linije` (`rbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMedjustanice`
    FOREIGN KEY (`id_medjustanica`)
    REFERENCES `piatest`.`stanice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`rezervacije_gradske`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`rezervacije_gradske` ;

CREATE TABLE IF NOT EXISTS `piatest`.`rezervacije_gradske` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `trajanje` INT(11) NOT NULL,
  `status` INT(11) NOT NULL,
  `cena` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`rezervacije_medjugradske`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`rezervacije_medjugradske` ;

CREATE TABLE IF NOT EXISTS `piatest`.`rezervacije_medjugradske` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  `prevoznik` VARCHAR(45) NOT NULL,
  `od_do` VARCHAR(80) NOT NULL,
  `cena` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`vozaci_gradske`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`vozaci_gradske` ;

CREATE TABLE IF NOT EXISTS `piatest`.`vozaci_gradske` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `datum_rodjenja` DATE NOT NULL,
  `poceo_sa_radom` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `piatest`.`vozac_linija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `piatest`.`vozac_linija` ;

CREATE TABLE IF NOT EXISTS `piatest`.`vozac_linija` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_linija` INT(11) NOT NULL,
  `id_vozac` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idLinija_idx` (`id_linija` ASC),
  INDEX `idVozaca_idx` (`id_vozac` ASC),
  CONSTRAINT `idLinija`
    FOREIGN KEY (`id_linija`)
    REFERENCES `piatest`.`gradske_linije` (`rbr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVozaca`
    FOREIGN KEY (`id_vozac`)
    REFERENCES `piatest`.`vozaci_gradske` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;

USE `piatest` ;

-- -----------------------------------------------------
-- Placeholder table for view `piatest`.`new_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piatest`.`new_view` (`id` INT, `prevoznik` INT, `linija` INT, `stanica` INT, `vozač` INT, `marka` INT, `dolazak` INT, `polazak` INT, `grupa` INT, `grupa_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `piatest`.`vw_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `piatest`.`vw_det` (`id` INT, `prevoznik` INT, `linija` INT, `stanica` INT, `vozač` INT, `marka` INT, `dolazak` INT, `polazak` INT, `grupa` INT, `grupa_id` INT);

-- -----------------------------------------------------
-- procedure guest_sort
-- -----------------------------------------------------

USE `piatest`;
DROP procedure IF EXISTS `piatest`.`guest_sort`;

DELIMITER $$
USE `piatest`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `guest_sort`(
	in datumm varchar(45),
	in prevoznikID int(11),
    in polazakOD timestamp,
    in polazakDO timestamp,
    in pocetak int(11),
    in kraj int(11)
)
BEGIN

TRUNCATE TABLE fill_ft_guest;
TRUNCATE TABLE medjustanice;

INSERT INTO fill_ft_guest(id,prevoznik,pocetna,odredisna,polazak,dolazak,vozac_id,autobus_id,vozac,autobus)
SELECT  pr.id as id ,p.naziv as Prevoznik,s1.naziv as pocetna,s2.naziv as odredisna, MIN(pd.polazak) as polazak,MAX(pd.dolazak) as dolazak, a.id, v.id, concat(v.ime," ",v.prezime) as vozac, concat(a.marka,"/",a.model) as Autobus
	FROM  prod pr, linije l, prevoznik_vozaci v,stanice s3, prevoznik p, stanice s1, stanice s2, linije_det ld, prod_det pd, prevoznik_autobusi a
		WHERE pr.linija_id=l.id AND COALESCE(pocetak,l.stanica0_id)=s1.id AND COALESCE(kraj,l.stanica1_id)=s2.id  AND pr.vozac_id = v.id AND v.prevoznik_id = p.id AND ld.linija_id = l.id AND pd.linijedet_id = ld.id AND pd.prod_id=pr.id
			AND s3.id = ld.stanica_id
            AND pr.autobus_id = a.id AND pd.linijedet_id=ld.id
			
            AND (prevoznikID IS NULL OR prevoznikID=p.id) 
            AND 
				(
                IF(pocetak IS NULL,ld.stanica_id = l.stanica0_id, IF(ld.stanica_id=pocetak,
					pd.polazak < (SELECT pd0.dolazak FROM prod_det pd0,linije_det ld0,linije l0,prod pr0 WHERE pr.id=pd0.prod_id AND ld0.id=pd0.linijedet_id AND ld0.linija_id=l0.id AND IF(kraj IS NULL,ld0.stanica_id=l0.stanica1_id,kraj=ld0.stanica_id) GROUP BY pd0.prod_id),false))
					OR 
				IF(kraj IS NULL, ld.stanica_id = l.stanica1_id, IF(ld.stanica_id=kraj,
					pd.dolazak > (SELECT pd0.dolazak FROM prod_det pd0,linije_det ld0,linije l0,prod pr0 WHERE pr.id=pd0.prod_id AND ld0.id=pd0.linijedet_id AND ld0.linija_id=l0.id AND IF(pocetak IS NULL,ld0.stanica_id=l0.stanica0_id,pocetak=ld0.stanica_id) GROUP BY pd0.prod_id),false))
                )
			
			GROUP BY pd.prod_id
			#HAVING IF(NOT(pocetak = NULL OR kraj = NULL), COUNT(*)=2, COUNT(*)>0);
			HAVING COUNT(*)=2 AND (datumm IS NULL OR (polazak between concat(datumm," ","00:00:00") AND concat(datumm," ","23:59:59")))AND (polazakOD IS NULL OR polazak >= polazakOD) AND (polazakDO IS NULL OR polazak<=polazakDO);
INSERT INTO medjustanice (prod_id,medjustanica)
SELECT ft.id as nid, s9.naziv as medjustanica 
	FROM prod_det pd9, prod pr9, linije_det ld9, stanice s9,fill_ft_guest ft 
		WHERE pd9.prod_id=pr9.id AND pd9.linijedet_id=ld9.id AND ld9.stanica_id=s9.id
			AND ft.id=pd9.prod_id AND ft.polazak < pd9.dolazak AND ft.dolazak > pd9.dolazak;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure new_procedure
-- -----------------------------------------------------

USE `piatest`;
DROP procedure IF EXISTS `piatest`.`new_procedure`;

DELIMITER $$
USE `piatest`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `new_procedure`(IN IDGrupe int)
BEGIN
SELECT 
        `det`.`id` AS `id`,
        `prevoz`.`naziv` AS `prevoznik`,
        `linije`.`opis` AS `linija`,
        `stanice`.`naziv` AS `stanica`,
        ((`vozac`.`ime` + ' ') + `vozac`.`prezime`) AS `vozač`,
        `bus`.`marka` AS `marka`,
        `det`.`dolazak` AS `dolazak`,
        `det`.`polazak` AS `polazak`,
        `gr`.`naziv` AS `grupa`,
        `gr`.`id` AS `grupa_id`
    FROM
        ((((((((`prevoznik` `prevoz`
        JOIN `prevoznik_vozaci` `vozac` ON ((`prevoz`.`id` = `vozac`.`prevoznik_id`)))
        JOIN `prevoznik_autobusi` `bus` ON ((`prevoz`.`id` = `bus`.`prevoznik_id`)))
        JOIN `prod` ON (((`bus`.`id` = `prod`.`autobus_id`)
            AND (`vozac`.`id` = `prod`.`vozac_id`))))
        JOIN `linije` ON ((`prod`.`linija_id` = `linije`.`id`)))
        JOIN `prod_det` `det` ON ((`prod`.`id` = `det`.`prod_id`)))
        JOIN `linije_det` `lindet` ON ((`linije`.`id` = `lindet`.`linija_id`)))
        JOIN `stanice` ON ((`lindet`.`stanica_id` = `stanice`.`id`)))
        JOIN `stanice_gr` `gr` ON ((`stanice`.`grupa_id` = `gr`.`id`)))
        WHERE (grupa_id = IDGrupe);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `piatest`.`new_view`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `piatest`.`new_view` ;
DROP TABLE IF EXISTS `piatest`.`new_view`;
USE `piatest`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `piatest`.`new_view` AS select `det`.`id` AS `id`,`prevoz`.`naziv` AS `prevoznik`,`piatest`.`linije`.`opis` AS `linija`,`piatest`.`stanice`.`naziv` AS `stanica`,concat(`vozac`.`ime`,' ',`vozac`.`prezime`) AS `vozač`,`bus`.`marka` AS `marka`,`det`.`dolazak` AS `dolazak`,`det`.`polazak` AS `polazak`,`gr`.`naziv` AS `grupa`,`gr`.`id` AS `grupa_id` from ((((((((`piatest`.`prevoznik` `prevoz` join `piatest`.`prevoznik_vozaci` `vozac` on((`prevoz`.`id` = `vozac`.`prevoznik_id`))) join `piatest`.`prevoznik_autobusi` `bus` on((`prevoz`.`id` = `bus`.`prevoznik_id`))) join `piatest`.`prod` on(((`bus`.`id` = `piatest`.`prod`.`autobus_id`) and (`vozac`.`id` = `piatest`.`prod`.`vozac_id`)))) join `piatest`.`linije` on((`piatest`.`prod`.`linija_id` = `piatest`.`linije`.`id`))) join `piatest`.`prod_det` `det` on((`piatest`.`prod`.`id` = `det`.`prod_id`))) join `piatest`.`linije_det` `lindet` on((`piatest`.`linije`.`id` = `lindet`.`linija_id`))) join `piatest`.`stanice` on((`lindet`.`stanica_id` = `piatest`.`stanice`.`id`))) join `piatest`.`stanice_gr` `gr` on((`piatest`.`stanice`.`grupa_id` = `gr`.`id`)));

-- -----------------------------------------------------
-- View `piatest`.`vw_det`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `piatest`.`vw_det` ;
DROP TABLE IF EXISTS `piatest`.`vw_det`;
USE `piatest`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `piatest`.`vw_det` AS select `det`.`id` AS `id`,`prevoz`.`naziv` AS `prevoznik`,`piatest`.`linije`.`opis` AS `linija`,`piatest`.`stanice`.`naziv` AS `stanica`,concat(`vozac`.`ime`,' ',`vozac`.`prezime`) AS `vozač`,`bus`.`marka` AS `marka`,`det`.`dolazak` AS `dolazak`,`det`.`polazak` AS `polazak`,`gr`.`naziv` AS `grupa`,`gr`.`id` AS `grupa_id` from ((((((((`piatest`.`prevoznik` `prevoz` join `piatest`.`prevoznik_vozaci` `vozac` on((`prevoz`.`id` = `vozac`.`prevoznik_id`))) join `piatest`.`prevoznik_autobusi` `bus` on((`prevoz`.`id` = `bus`.`prevoznik_id`))) join `piatest`.`prod` on(((`bus`.`id` = `piatest`.`prod`.`autobus_id`) and (`vozac`.`id` = `piatest`.`prod`.`vozac_id`)))) join `piatest`.`linije` on((`piatest`.`prod`.`linija_id` = `piatest`.`linije`.`id`))) join `piatest`.`prod_det` `det` on((`piatest`.`prod`.`id` = `det`.`prod_id`))) join `piatest`.`linije_det` `lindet` on((`piatest`.`linije`.`id` = `lindet`.`linija_id`))) join `piatest`.`stanice` on((`lindet`.`stanica_id` = `piatest`.`stanice`.`id`))) join `piatest`.`stanice_gr` `gr` on((`piatest`.`stanice`.`grupa_id` = `gr`.`id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('BG TOURS','Jovana Cvijica 12','0612838127');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Nis Express','Macvanska 32','0612332927');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Bugojno prevoz','Sajamski put 23','0613322888');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Semberija Transport','Gavrila Principa 23','0612999232');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Eurolines','Radomir Putnik 10','0616612999');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Bus Serbia','Zeleznicka stanica 12','0616192327');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Booba Tours','27 marta 12','0612232327');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Golubic Tours','Milutina Milankovica 21','0619192327');
INSERT INTO prevoznik(naziv,adresa,kontakt) VALUES ('Dedinje Tours','Dedinje','061651231');

INSERT INTO stanice(naziv) VALUES ('Valjevo');
INSERT INTO stanice(naziv) VALUES ('Vranje');
INSERT INTO stanice(naziv) VALUES ('Zajecar');
INSERT INTO stanice(naziv) VALUES ('Zrenjanin');
INSERT INTO stanice(naziv) VALUES ('Jagodina');
INSERT INTO stanice(naziv) VALUES ('Kragujevac');
INSERT INTO stanice(naziv) VALUES ('Kraljevo');
INSERT INTO stanice(naziv) VALUES ('Krusevac');
INSERT INTO stanice(naziv) VALUES ('Valjevo');
INSERT INTO stanice(naziv) VALUES ('Leskovac');
INSERT INTO stanice(naziv) VALUES ('Loznica');
INSERT INTO stanice(naziv) VALUES ('Nis');
INSERT INTO stanice(naziv) VALUES ('Novi Pazar');
INSERT INTO stanice(naziv) VALUES ('Novi Sad');
INSERT INTO stanice(naziv) VALUES ('Pancevo');
INSERT INTO stanice(naziv) VALUES ('Pozarevac');
INSERT INTO stanice(naziv) VALUES ('Smederevo');
INSERT INTO stanice(naziv) VALUES ('Sombor');
INSERT INTO stanice(naziv) VALUES ('Sremska Mitrovica');
INSERT INTO stanice(naziv) VALUES ('Subotica');
INSERT INTO stanice(naziv) VALUES ('Uzice');
INSERT INTO stanice(naziv) VALUES ('Cacak');
INSERT INTO stanice(naziv) VALUES ('Sabac');
INSERT INTO stanice(naziv) VALUES ('Beograd');

INSERT INTO stanice(naziv) VALUES ('Pristaniste');
INSERT INTO stanice(naziv) VALUES ('Vukov spomenik');
INSERT INTO stanice(naziv) VALUES ('Tehnicki fakulteti');
INSERT INTO stanice(naziv) VALUES ('Pravni fakultet');
INSERT INTO stanice(naziv) VALUES ('Tasmajdan');
INSERT INTO stanice(naziv) VALUES ('Resavska');
INSERT INTO stanice(naziv) VALUES ('Beogradjanka');
INSERT INTO stanice(naziv) VALUES ('Zeleznicka stanica');
INSERT INTO stanice(naziv) VALUES ('Dalmatinska');
INSERT INTO stanice(naziv) VALUES ('Omladinski stadion');
INSERT INTO stanice(naziv) VALUES ('Marijane Gregoran');
INSERT INTO stanice(naziv) VALUES ('Novo groblje');
INSERT INTO stanice(naziv) VALUES ('Salvadora Aljendea');
INSERT INTO stanice(naziv) VALUES ('Karaburma okretnica');
INSERT INTO stanice(naziv) VALUES ('Masinski fakultet');
INSERT INTO stanice(naziv) VALUES ('Botanicka basta');
INSERT INTO stanice(naziv) VALUES ('Skadarska');
INSERT INTO stanice(naziv) VALUES ('Zeleni venac');
INSERT INTO stanice(naziv) VALUES ('Usce');
INSERT INTO stanice(naziv) VALUES ('Zemun');
INSERT INTO stanice(naziv) VALUES ('Blok 45');
INSERT INTO stanice(naziv) VALUES ('Ustanicka');
INSERT INTO stanice(naziv) VALUES ('Lion');
INSERT INTO stanice(naziv) VALUES ('Djeram pijaca');
INSERT INTO stanice(naziv) VALUES ('Batutova');
INSERT INTO stanice(naziv) VALUES ('Calije');